services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    command: redis-server
    volumes:
      - redis_data:/data
    environment:
      - maxmemory=256mb
      - maxmemory-policy=volatile-lru
    networks:
      - network-hs

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.9.0
    restart: always
    ports:
      - '${KAFKA_PORT}:${KAFKA_PORT}'
    volumes:
      - 'kafka_data:/data'
    networks:
      - network-hs
    environment:
      # kraft
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

      - KAFKA_HEAP_OPTS=-Xmx256m -Xms256m
      # - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # - ALLOW_PLAINTEXT_LISTENER=yes
      # KAFKA_KRAFT_CLUSTER_ID not set - If using multiple nodes then you must use the same Cluster ID for each one
      # Kafka has been configured with a PLAINTEXT listener, this setting is not recommended for production environments.

  pgadmin4:
    image: elestio/pgadmin:REL-8_10
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_PORT}
      - TZ=Asia/Seoul
    ports:
      - '${PGADMIN_PORT}:${PGADMIN_PORT}'
    networks:
      - network-hs

volumes:
  redis_data:
  kafka_data:

networks:
  network-hs:
    external: true
