# version: '3.9' 이제 compose에서 버전을 지정하지 않음

# services: 실행할 서비스들을 정의
services:
  app:
    container_name: app
    build: . # Dockerfile이 있는 경로 (절대경로 또는 상대경로) # 현재 디렉토리의 도커파일 빌드
    env_file: # .env 파일을 지정하여 환경 변수를 로드
      # - .env.development
      - .env
    restart: always
    ports:
      - '${PORT}:${PORT}' # 외부 포트 : 내부 포트
    volumes: # 외부 경로 : 컨테이너 내부 경로
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

networks:
  hs-network:
    external: true
